import React, { useState, useEffect } from 'react';
import { Spin } from 'antd';
import { Loader, Card, FormField } from '../components';
function Home() {
	const [loading, isLoading] = useState(true);
	const [allPosts, setAllPosts] = useState([null]);
	return (
		<section className='max-w-7xl mx-auto'>
			<div>
				<h1 className='font-extrabold text-[32px]'>The Community Showcase</h1>
				<p className='mt-2 text-[#666e74] text-[16px] max-w[500px]'>
					Browes through a collection of imagiative and visually stunning images
					generated by DALL-E AI
				</p>
			</div>

			<div className='mt-16'>
				<FormField />
			</div>

			<div className='mt-10'>
				{loading ? (
					<div className='flex justify-center items-center'>
						<Spin />
					</div>
				) : (
					<></>
				)}
			</div>
		</section>
	);
}

export default Home;
